// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// BrowseParams is the params shape for action "address.browse (List Likely Files)".
type BrowseParams struct {
}

// HandleBrowse registers a typed handler for action "address.browse (List Likely Files)".
func HandleBrowse(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("address.browse", fn)
}

// DismissParams is the params shape for action "address.dismiss (Close the File Choices)".
type DismissParams struct {
}

// HandleDismiss registers a typed handler for action "address.dismiss (Close the File Choices)".
func HandleDismiss(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("address.dismiss", fn)
}

// InsertParams is the params shape for action "address.insert (Type a File's Address)".
type InsertParams struct {
	Path string `json:"path"`
}

// HandleInsert registers a typed handler for action "address.insert (Type a File's Address)".
func HandleInsert(p *branchkit.Plugin, fn func(InsertParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "address.insert", fn)
}

// MentionParams is the params shape for action "address.mention (Mention a File)".
type MentionParams struct {
	Name string `json:"name"`
}

// HandleMention registers a typed handler for action "address.mention (Mention a File)".
func HandleMention(p *branchkit.Plugin, fn func(MentionParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "address.mention", fn)
}
