// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

package main

import "github.com/branchkit/plugin-sdk-go"

// CiteParams is the params shape for action "address.cite (Cite a File)".
type CiteParams struct {
	Name string `json:"name"`
}

// HandleCite registers a typed handler for action "address.cite (Cite a File)".
func HandleCite(p *branchkit.Plugin, fn func(CiteParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "address.cite", fn)
}

// DismissParams is the params shape for action "address.dismiss (Close the File Choices)".
type DismissParams struct {
}

// HandleDismiss registers a typed handler for action "address.dismiss (Close the File Choices)".
func HandleDismiss(p *branchkit.Plugin, fn branchkit.ActionHandlerFunc) {
	p.HandleAction("address.dismiss", fn)
}

// InsertParams is the params shape for action "address.insert (Type a File's Address)".
type InsertParams struct {
	Path string `json:"path"`
}

// HandleInsert registers a typed handler for action "address.insert (Type a File's Address)".
func HandleInsert(p *branchkit.Plugin, fn func(InsertParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "address.insert", fn)
}
