// Code generated by branchkit-gen from plugin.json `consumes.collections`. DO NOT EDIT.
// Field types come from each provider's declared schema: the platform's
// collections, or a provider plugin in a directory beside this one.
// Regenerate from the parent directory: branchkit-gen --plugin <this plugin's directory>

package main

// AlphabetRecord is the shape this plugin declared it reads from the
// "alphabet" collection. Unmarshal a CollectionRecord's Payload into it.
type AlphabetRecord struct {
	Codeword string `json:"codeword"`
}
